### ISSUE TITLE
An unexpected error occurred: SQLite objects

### ISSUE THREAD

**Issue by dziq** [draga79/NotiMail#2]
I have an error when NotiMail try to get e-mail form second account defined in config.ini but script still works.

`An unexpected error occurred: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140
305123428160 and this is thread id 140305096615680.
Failed to send notification to https://ntfy.nitkiewicz.me/mail. Status Code: 403`
`* OK Still here`

This one is for first account defined in config.ini. After error script stops.
`IDLE mode stopped.
An unexpected error occurred: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140
305123428160 and this is thread id 140305105008384.
Failed to send notification to https://ntfy.nitkiewicz.me/mail. Status Code: 403
Logging out and closing the connection...
Traceback (most recent call last):
  File "/home/dziq/NotiMail/NotiMail.py", line 426, in <module>
    multi_account_main()
  File "/home/dziq/NotiMail/NotiMail.py", line 423, in multi_account_main
    processor.db_handler.close()
NameError: name 'processor' is not defined`

**Comment by draga79** [comment]
I have commited some fixes, could you please try again? Thank you!

**Comment by draga79** [comment]
The last fixes should have solved this issue
