### ISSUE TITLE
Ntfy authentication

### ISSUE THREAD

**Issue by dziq** [draga79/NotiMail#3]
I have small suggestion. Could you please add authentication option for ntfy. I have my own instance of ntfy and I've configure it to only get notifications from authenticated sources. It works but I have to add header definition to NotiMail.py like ntfy has in its docs [https://docs.ntfy.sh/publish/#authentication](url).

**Comment by draga79** [comment]
I've just pushed the last commits with optional ntfy authentication (via token). You can add a Token configuration option in the config.ini (for example: Url1 will use Token1 if present) and it will be used to push notifications.
It'll be a part of the 0.10 release, for now it's in the master - please test and let me know if you encounter problems.
