### ISSUE TITLE
`Config`: Location of SQL DB and log file should be definable

### ISSUE THREAD

**Issue by gyptazy** [draga79/NotiMail#5]
## General
Currently, the location of the SQL database and the log file are hardcoded. However, users might want to relocate them. Instead of modifying the code this should be easy adjustable for enduser from the config file. Next to it, it might be helpful to pass multiple config files to have different setups running or to use it as a daemon in a multi user setup.

## Task(s)
* Use `argparse` or similar to pass a config file to `NotiMail`
* Create a `[GENERAL]` chapter within the ini config file
    * Create a config item for `LogFileLocation`
    * Create a config item for `DataBaseLocation`
* Adjust the programs routine
    * Pre-evaluate the passed config
    * Pass the config path to the log config (set default if unset)
    * Pass the config path to the db location (set default if unset)

If you like I can provide a PR for this but it might be by the end of the week.

**Comment by draga79** [comment]
I was already working on config and log location as I'm preparing a port for FreeBSD and OpenBSD, so I need them to be in the right place. 
It'll be implemented as soon as I'll have identified and solved the timeout problems

**Comment by draga79** [comment]
Ok, today I had too many (BSD) coffees. I think I fixed it, should be ok. I had already implemented the code, but followed your PR request for names and configuration options.

**Comment by gyptazy** [comment]
Awesome! That was fast! Thanks
