### ISSUE TITLE
Notifying on emails received in other folders

### ISSUE THREAD

**Issue by Amolith** [draga79/NotiMail#6]
My spam filtration system is a bit overzealous and very often routes legitimate emails to my JUNK folder, especially when it comes through [Firefox Relay](https://relay.firefox.com/). It would be nice if I could tell NotiMail to yell at me when I get an email in my JUNK folders in addition to the INBOX folder.

I'm happy to take a look at implementing it myself, but I won't have any extra time for the next few weeks.

**Comment by draga79** [comment]
I'm also interested in monitoring multiple folders, so I'll be implementing it ASAP.

**Comment by draga79** [comment]
Ok, I've implemented it. 
Version 0.12 is out, with this and other new features (new command line options to print and test config.ini configuration and list mailbox folders)
Please let me know if you find any problems or have any suggestions.
